### PR TITLE
Update libxml-ruby version

### PR DESCRIPTION
**Pull request by hainesr**
Been seeing seg-faults with libxml-ruby 2.6 and would like to update, but ratom prevents this. Can we loosen the requirements a bit please?

### CODE REVIEW

**Comment by seangeo** [comment]
Thanks. Will get a new release out soon.

**Comment by hainesr** [comment]
Great, thanks.

**Comment by hainesr** [comment]
Hi, sorry to bug you but could we have that new release please?

Thanks!

**Comment by AndrewKvalheim** [comment]
Just a heads-up—ratom [support][pr] for Ruby 2.2.0 is pending this release.


  [pr]: https://github.com/xml4r/libxml-ruby/pull/99

**Comment by seangeo** [comment]
So for the delay! https://rubygems.org/gems/ratom/versions/0.9.0

**Comment by hainesr** [comment]
Thanks!

**Pull request merged**
